_wandb:
    value:
        cli_version: 0.23.0
        e:
            gtri5rauqxemll0e2eifv3asczk08yle:
                codePath: train_model.py
                codePathLocal: train_model.py
                cpu_count: 32
                cpu_count_logical: 64
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "3778773131264"
                        used: "3367768903680"
                email: peneetaw@gmail.com
                executable: /home/WS_Tiger/miniconda3/envs/pyML/bin/python
                git:
                    commit: 30503834e255892838f7a30b98fd86a773125f5a
                    remote: git@github.com:peneeta/neuro-ml-capstone.git
                gpu: NVIDIA RTX 6000 Ada Generation
                gpu_count: 2
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 18176
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX 6000 Ada Generation
                      uuid: GPU-8e1a0daf-ac1e-95b0-4b75-bb0d4dc99ec3
                    - architecture: Ada
                      cudaCores: 18176
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX 6000 Ada Generation
                      uuid: GPU-5f131a06-f898-6017-f376-86e1d412f27b
                host: Zhaolab
                memory:
                    total: "540626751488"
                os: Linux-6.8.0-87-generic-x86_64-with-glibc2.35
                program: /home/WS_Tiger/em_capstone_f25/neuro-ml-capstone/train_model.py
                python: CPython 3.11.14
                root: /home/WS_Tiger/em_capstone_f25/neuro-ml-capstone
                startedAt: "2025-12-08T16:47:31.574732Z"
                writerId: gtri5rauqxemll0e2eifv3asczk08yle
        m: []
        python_version: 3.11.14
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 16
            "4": 3.11.14
            "5": 0.23.0
            "12": 0.23.0
            "13": linux-x86_64
epochs:
    value: 40
learning_rate:
    value: 0.001
loss_function:
    value: SSIM
model_name:
    value: NeuroUNET
